# -*- coding: utf-8 -*-
"""conditional_multimodal_vae_brats_dummy_test_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpzcKlUpFt4C3QiGbLyf9OzsKgRbOFRe

# Conditional Multimodal VAE — Dummy Tensor Build and Test

This notebook builds and tests a conditional multimodal VAE using dummy tensors.

## What this notebook does
- builds the encoder, `mu`, `logvar`, sampling, and decoder
- uses reconstruction MSE + KL divergence
- tests three synthesis setups with dummy tensors
- runs a forward pass
- runs one custom training step
- prints tensor shapes to verify the pipeline

## Dummy tensor convention
The requested dummy tensor shape is:

`(batch, 1, 240, 240)`

TensorFlow `Conv2D` expects channel-last by default, so the notebook converts tensors to:

`(batch, 240, 240, 1)`

before model use.
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import Tuple

print("TensorFlow version:", tf.__version__)

"""## Configuration and helpers"""

@dataclass
class VAEConfig:
    image_size: Tuple[int, int] = (240, 240)
    in_channels: int = 3
    out_channels: int = 1
    latent_dim: int = 64
    beta: float = 1e-4
    learning_rate: float = 1e-4
    batch_size: int = 2
    encoder_filters: Tuple[int, ...] = (32, 64, 128, 256)
    decoder_filters: Tuple[int, ...] = (256, 128, 64, 32)
    seed: int = 42

def set_seed(seed: int = 42) -> None:
    np.random.seed(seed)
    tf.random.set_seed(seed)

def to_channels_last(x: np.ndarray) -> np.ndarray:
    if x.ndim != 4:
        raise ValueError(f"Expected 4D tensor, got shape {x.shape}")
    return np.transpose(x, (0, 2, 3, 1)).astype(np.float32)

def make_dummy_tensor(batch: int, height: int = 240, width: int = 240) -> np.ndarray:
    return np.random.rand(batch, 1, height, width).astype(np.float32)

"""## VAE building blocks"""

class Sampling(layers.Layer):
    def call(self, inputs, training=None):
        mu, logvar = inputs
        eps = tf.random.normal(shape=tf.shape(mu))
        sigma = tf.exp(0.5 * logvar)
        return mu + sigma * eps

def build_encoder(config: VAEConfig):
    h, w = config.image_size
    x_in = keras.Input(shape=(h, w, config.in_channels), name="encoder_input")

    x = x_in
    for i, f in enumerate(config.encoder_filters):
        x = layers.Conv2D(f, kernel_size=3, strides=2, padding="same", name=f"enc_conv_{i}")(x)
        x = layers.BatchNormalization(name=f"enc_bn_{i}")(x)
        x = layers.LeakyReLU(negative_slope=0.2, name=f"enc_lrelu_{i}")(x)

    shape_before_flatten = tuple(int(d) for d in x.shape[1:])
    x = layers.Flatten(name="enc_flatten")(x)
    x = layers.Dense(256, activation="relu", name="enc_dense")(x)

    mu = layers.Dense(config.latent_dim, name="z_mu")(x)
    logvar = layers.Dense(config.latent_dim, name="z_logvar")(x)
    z = Sampling(name="z_sampling")([mu, logvar])

    encoder = keras.Model(x_in, [mu, logvar, z], name="encoder")
    return encoder, shape_before_flatten

def build_decoder(config: VAEConfig, shape_before_flatten):
    z_in = keras.Input(shape=(config.latent_dim,), name="z_input")

    x = layers.Dense(256, activation="relu", name="dec_dense_0")(z_in)
    x = layers.Dense(int(np.prod(shape_before_flatten)), activation="relu", name="dec_dense_1")(x)
    x = layers.Reshape(shape_before_flatten, name="dec_reshape")(x)

    for i, f in enumerate(config.decoder_filters):
        x = layers.Conv2DTranspose(f, kernel_size=3, strides=2, padding="same", name=f"dec_deconv_{i}")(x)
        x = layers.BatchNormalization(name=f"dec_bn_{i}")(x)
        x = layers.LeakyReLU(negative_slope=0.2, name=f"dec_lrelu_{i}")(x)

    x = layers.Conv2D(config.out_channels, kernel_size=3, padding="same", activation="sigmoid", name="decoder_output_conv")(x)
    x = layers.Resizing(config.image_size[0], config.image_size[1], name="decoder_resize")(x)

    return keras.Model(z_in, x, name="decoder")

class ConditionalVAE(keras.Model):
    def __init__(self, config: VAEConfig, **kwargs):
        super().__init__(**kwargs)
        self.config = config
        self.encoder, shape_before_flatten = build_encoder(config)
        self.decoder = build_decoder(config, shape_before_flatten)

        self.total_loss_tracker = keras.metrics.Mean(name="total_loss")
        self.recon_loss_tracker = keras.metrics.Mean(name="recon_loss")
        self.kl_loss_tracker = keras.metrics.Mean(name="kl_loss")

    @property
    def metrics(self):
        return [self.total_loss_tracker, self.recon_loss_tracker, self.kl_loss_tracker]

    def call(self, x, training=False):
        mu, logvar, z = self.encoder(x, training=training)
        recon = self.decoder(z, training=training)
        return recon, mu, logvar, z

    def compute_losses(self, x, y, training=False):
        recon, mu, logvar, z = self(x, training=training)
        recon_mse = tf.reduce_mean(tf.math.squared_difference(y, recon), axis=(1, 2, 3))
        recon_loss = tf.reduce_mean(recon_mse)
        kl_per_sample = -0.5 * tf.reduce_sum(1.0 + logvar - tf.square(mu) - tf.exp(logvar), axis=1)
        kl_loss = tf.reduce_mean(kl_per_sample)
        total_loss = recon_loss + self.config.beta * kl_loss
        return total_loss, recon_loss, kl_loss, recon, mu, logvar, z

    def train_step_batch(self, optimizer, x, y):
        with tf.GradientTape() as tape:
            total_loss, recon_loss, kl_loss, recon, mu, logvar, z = self.compute_losses(x, y, training=True)

        grads = tape.gradient(total_loss, self.trainable_variables)
        optimizer.apply_gradients(zip(grads, self.trainable_variables))

        self.total_loss_tracker.update_state(total_loss)
        self.recon_loss_tracker.update_state(recon_loss)
        self.kl_loss_tracker.update_state(kl_loss)

        return {
            "total_loss": float(total_loss.numpy()),
            "recon_loss": float(recon_loss.numpy()),
            "kl_loss": float(kl_loss.numpy()),
            "recon_shape": tuple(recon.shape),
            "mu_shape": tuple(mu.shape),
            "logvar_shape": tuple(logvar.shape),
            "z_shape": tuple(z.shape),
        }

"""## Create dummy tensors"""

set_seed(42)

batch = 2
H = 240
W = 240

t1_cf = make_dummy_tensor(batch, H, W)
t2_cf = make_dummy_tensor(batch, H, W)
t1ce_cf = make_dummy_tensor(batch, H, W)
flair_cf = make_dummy_tensor(batch, H, W)

print("Channel-first shapes:")
print("t1   :", t1_cf.shape)
print("t2   :", t2_cf.shape)
print("t1ce :", t1ce_cf.shape)
print("flair:", flair_cf.shape)

t1 = to_channels_last(t1_cf)
t2 = to_channels_last(t2_cf)
t1ce = to_channels_last(t1ce_cf)
flair = to_channels_last(flair_cf)

print("\nChannel-last shapes:")
print("t1   :", t1.shape)
print("t2   :", t2.shape)
print("t1ce :", t1ce.shape)
print("flair:", flair.shape)

"""## Build the three dummy synthesis tasks"""

X_t1ce = np.concatenate([t1, t2, flair], axis=-1).astype(np.float32)
Y_t1ce = t1ce.astype(np.float32)

X_flair = np.concatenate([t1, t2, t1ce], axis=-1).astype(np.float32)
Y_flair = flair.astype(np.float32)

X_t1t2 = np.concatenate([t1ce, flair], axis=-1).astype(np.float32)
Y_t1t2 = np.concatenate([t1, t2], axis=-1).astype(np.float32)

print("Task A input/output:", X_t1ce.shape, Y_t1ce.shape)
print("Task B input/output:", X_flair.shape, Y_flair.shape)
print("Task C input/output:", X_t1t2.shape, Y_t1t2.shape)

"""## Build and test Task A: T1ce synthesis"""

config_a = VAEConfig(image_size=(240, 240), in_channels=3, out_channels=1, latent_dim=64, batch_size=batch)
model_a = ConditionalVAE(config_a)
optimizer_a = keras.optimizers.Adam(learning_rate=config_a.learning_rate)

total_loss, recon_loss, kl_loss, recon, mu, logvar, z = model_a.compute_losses(X_t1ce, Y_t1ce, training=False)

print("Task A forward pass")
print("Input shape    :", X_t1ce.shape)
print("Target shape   :", Y_t1ce.shape)
print("Recon shape    :", recon.shape)
print("Mu shape       :", mu.shape)
print("Logvar shape   :", logvar.shape)
print("Latent z shape :", z.shape)
print("Total loss     :", float(total_loss.numpy()))
print("Recon loss     :", float(recon_loss.numpy()))
print("KL loss        :", float(kl_loss.numpy()))

train_logs_a = model_a.train_step_batch(optimizer_a, X_t1ce, Y_t1ce)
print("\nTask A one training step:")
print(train_logs_a)

"""## Build and test Task B: FLAIR synthesis"""

config_b = VAEConfig(image_size=(240, 240), in_channels=3, out_channels=1, latent_dim=64, batch_size=batch)
model_b = ConditionalVAE(config_b)
optimizer_b = keras.optimizers.Adam(learning_rate=config_b.learning_rate)

total_loss, recon_loss, kl_loss, recon, mu, logvar, z = model_b.compute_losses(X_flair, Y_flair, training=False)

print("Task B forward pass")
print("Input shape    :", X_flair.shape)
print("Target shape   :", Y_flair.shape)
print("Recon shape    :", recon.shape)
print("Mu shape       :", mu.shape)
print("Logvar shape   :", logvar.shape)
print("Latent z shape :", z.shape)
print("Total loss     :", float(total_loss.numpy()))
print("Recon loss     :", float(recon_loss.numpy()))
print("KL loss        :", float(kl_loss.numpy()))

train_logs_b = model_b.train_step_batch(optimizer_b, X_flair, Y_flair)
print("\nTask B one training step:")
print(train_logs_b)

"""## Build and test Task C: joint T1 + T2 synthesis"""

config_c = VAEConfig(image_size=(240, 240), in_channels=2, out_channels=2, latent_dim=64, batch_size=batch)
model_c = ConditionalVAE(config_c)
optimizer_c = keras.optimizers.Adam(learning_rate=config_c.learning_rate)

total_loss, recon_loss, kl_loss, recon, mu, logvar, z = model_c.compute_losses(X_t1t2, Y_t1t2, training=False)

print("Task C forward pass")
print("Input shape    :", X_t1t2.shape)
print("Target shape   :", Y_t1t2.shape)
print("Recon shape    :", recon.shape)
print("Mu shape       :", mu.shape)
print("Logvar shape   :", logvar.shape)
print("Latent z shape :", z.shape)
print("Total loss     :", float(total_loss.numpy()))
print("Recon loss     :", float(recon_loss.numpy()))
print("KL loss        :", float(kl_loss.numpy()))

train_logs_c = model_c.train_step_batch(optimizer_c, X_t1t2, Y_t1t2)
print("\nTask C one training step:")
print(train_logs_c)

"""## Quick reconstruction preview"""

fig, axes = plt.subplots(2, 3, figsize=(10, 6))

pred_a, _, _, _ = model_a(X_t1ce, training=False)
axes[0, 0].imshow(np.mean(X_t1ce[0], axis=-1), cmap="gray")
axes[0, 0].set_title("Task A input")
axes[0, 1].imshow(Y_t1ce[0, :, :, 0], cmap="gray")
axes[0, 1].set_title("Task A target")
axes[0, 2].imshow(pred_a.numpy()[0, :, :, 0], cmap="gray")
axes[0, 2].set_title("Task A prediction")

pred_c, _, _, _ = model_c(X_t1t2, training=False)
axes[1, 0].imshow(np.mean(X_t1t2[0], axis=-1), cmap="gray")
axes[1, 0].set_title("Task C input")
axes[1, 1].imshow(Y_t1t2[0, :, :, 0], cmap="gray")
axes[1, 1].set_title("Task C target ch0")
axes[1, 2].imshow(pred_c.numpy()[0, :, :, 0], cmap="gray")
axes[1, 2].set_title("Task C pred ch0")

for row in axes:
    for ax in row:
        ax.axis("off")

plt.tight_layout()
plt.show()

"""## Summary

This notebook is a sanity-check notebook for the architecture. It verifies:
- build success
- forward pass success
- loss computation success
- one custom training step success

It uses dummy tensors that start as `(batch, 1, 240, 240)` and are converted to TensorFlow channel-last format before use.

"""