# -*- coding: utf-8 -*-
"""conditional_multimodal_vae_brats_real_data_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A51DDrSwWD1XM04zIhF0KndXxkgirtPr

# Conditional Multimodal VAE — Real BraTS Data

This notebook builds and tests a Conditional Multimodal VAE using **real BraTS data** loaded from Google Drive (`/content/drive/MyDrive/Group_Project_766/`).

## What this notebook does
- Builds the encoder (`mu`, `logvar`, sampling) and decoder
- Uses reconstruction MSE + KL divergence loss
- Tests three synthesis setups with real patient `.npz` slices
- Runs forward passes and one custom training step per task
- Prints tensor shapes to verify the full pipeline

## Dummy tensor convention
Yue's preprocessing saves slices as **channels-first** `(batch, C, H, W)`.  
This notebook uses `channels_first` throughout to match that convention — no intermediate transposes.

## Summary of fixes applied

| # | Severity | Issue | Fix applied |
|---|----------|-------|-------------|
| 1 | **CRITICAL** | Sigmoid output can't produce z-scored values | `activation=None` (linear) |
| 2 | **CRITICAL** | TF vs PyTorch framework mismatch | Stays TF/Keras; team decision note added |
| 3 | **CRITICAL** | Channel-ordering conversions | `channels_first` globally; transpose removed |
| 4 | MEDIUM | `beta=1e-4` makes KL negligible | `beta=1.0` + `BetaScheduler` annealing |
| 5 | MEDIUM | `latent_dim=64` too small for 240×240 | `latent_dim=128` |
| 6 | MEDIUM | `Flatten+Dense(256)` spatial bottleneck | `GlobalAveragePooling2D` |
| 7 | MEDIUM | No dropout | `Dropout(0.2)` after `enc_dense` and `dec_dense_0` |
| 8 | LOW | Resizing layer masks shape mismatch | Removed; output is exactly 240×240 |
| 9 | LOW | Dummy loader won't match real data | `load_real_data_stub` added |
| 10 | LOW | No LR scheduler | `ReduceLROnPlateau` stub documented |
| 11 | LOW | No gradient clipping | `clipnorm=1.0` on all optimisers |
| 12 | LOW | Task C harder than single-modality | Note added in Task C section |

---
## 1. Imports & Global Setup
"""

import os
import glob
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
from dataclasses import dataclass, field
from typing import Tuple

# FIX #3 (CRITICAL): Use channels-first globally to match Yue's preprocessing
# output format (4, 240, 240). Eliminates the need for to_channels_last transposes.
tf.keras.backend.set_image_data_format('channels_first')

print("TensorFlow version:", tf.__version__)
print("Image data format :", tf.keras.backend.image_data_format())  # should print 'channels_first'

"""> **Framework decision note (FIX #2 — CRITICAL)**  
> This VAE is implemented in **TensorFlow/Keras** (consistent with course material).  
> David's U-Net must also use TensorFlow/Keras for the INT-01 integration pipeline to work without framework-bridging overhead.  
> If the team decides to switch the U-Net to PyTorch, this VAE should be ported at that point.  
> **The decision must be made before Sprint C begins.**

---
## 2. Configuration and Helpers
"""

@dataclass
class VAEConfig:
    image_size: Tuple[int, int] = (240, 240)
    in_channels: int = 3
    out_channels: int = 1
    latent_dim: int = 128        # FIX #5 (MEDIUM): raised from 64 → 128
    beta: float = 1.0            # FIX #4 (MEDIUM): raised; BetaScheduler handles annealing
    learning_rate: float = 1e-4
    batch_size: int = 2
    encoder_filters: Tuple[int, ...] = (32, 64, 128, 256)
    decoder_filters: Tuple[int, ...] = (256, 128, 64, 32)
    seed: int = 42
    dropout_rate: float = 0.2    # FIX #7 (MEDIUM): dropout for Dense layers


def set_seed(seed: int = 42) -> None:
    np.random.seed(seed)
    tf.random.set_seed(seed)


# ── Google Drive mount ────────────────────────────────────────────────────────
# Run this block once per Colab session to mount your St Thomas OneDrive.
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)
    print("Google Drive mounted.")
except ImportError:
    print("Not running in Colab — skipping drive mount.")

DATA_DIR = "/content/drive/MyDrive/Group_Project_766/"


# ── Real-data loader ──────────────────────────────────────────────────────────
def load_npz_slice(npz_path: str, target_channel_idx: int):
    """
    Load one preprocessed BraTS slice from a .npz file and return
    channels-first (batch=1) tensors ready for the VAE.

    Expected .npz layout (Yue's preprocessing):
        data["slice"]  →  shape (4, 240, 240)   float32, z-scored
            channel 0 = T1
            channel 1 = T2
            channel 2 = T1ce
            channel 3 = FLAIR

    Parameters
    ----------
    npz_path : str
        Absolute path to the .npz file.
    target_channel_idx : int
        Which channel is the synthesis target (0–3).

    Returns
    -------
    x : np.ndarray  shape (1, 3, 240, 240)  — three input modalities
    y : np.ndarray  shape (1, 1, 240, 240)  — target modality
    """
    data = np.load(npz_path)
    # ── key detection: try common export keys ────────────────────────────────
    for key in ("slice", "data", "arr_0"):
        if key in data:
            all_channels = data[key]
            break
    else:
        raise KeyError(
            f"Could not find a recognised key in {npz_path}. "
            f"Available keys: {list(data.keys())}"
        )

    if all_channels.shape != (4, 240, 240):
        raise ValueError(
            f"Expected shape (4, 240, 240), got {all_channels.shape} in {npz_path}"
        )

    y = all_channels[target_channel_idx : target_channel_idx + 1][np.newaxis]  # (1,1,240,240)
    input_channels = np.delete(all_channels, target_channel_idx, axis=0)        # (3,240,240)
    x = input_channels[np.newaxis]                                               # (1,3,240,240)
    return x.astype(np.float32), y.astype(np.float32)


def load_batch(file_list: list, target_channel_idx: int):
    """
    Stack multiple slices into a single batch tensor.

    Parameters
    ----------
    file_list : list[str]
        Absolute paths to .npz files (one per slice).
    target_channel_idx : int
        Synthesis target channel (0=T1, 1=T2, 2=T1ce, 3=FLAIR).

    Returns
    -------
    X : np.ndarray  shape (N, 3, 240, 240)
    Y : np.ndarray  shape (N, 1, 240, 240)
    """
    xs, ys = [], []
    for path in file_list:
        x, y = load_npz_slice(path, target_channel_idx)
        xs.append(x)
        ys.append(y)
    return np.concatenate(xs, axis=0), np.concatenate(ys, axis=0)


def discover_npz_files(data_dir: str, limit: int = None) -> list:
    """
    Recursively find all .npz files under data_dir.

    Parameters
    ----------
    data_dir : str
        Root folder on Google Drive, e.g. DATA_DIR.
    limit : int, optional
        Cap the list (useful for quick sanity checks).

    Returns
    -------
    list[str]  — sorted absolute paths
    """
    import glob
    pattern = os.path.join(data_dir, "**", "*.npz")
    files = sorted(glob.glob(pattern, recursive=True))
    if not files:
        raise FileNotFoundError(
            f"No .npz files found under {data_dir}. "
            "Check that the Drive is mounted and the path is correct."
        )
    if limit is not None:
        files = files[:limit]
    return files


# ── FIX #4 (MEDIUM): Beta annealer ───────────────────────────────────────────
class BetaScheduler:
    """
    Linearly anneals beta from 0.0 to beta_max over `warmup_epochs` epochs.
    Using beta=0 for the first few epochs lets the encoder learn useful
    features before the KL constraint is applied.
    """
    def __init__(self, beta_max: float = 1.0, warmup_epochs: int = 10):
        self.beta_max = beta_max
        self.warmup_epochs = warmup_epochs

    def get(self, epoch: int) -> float:
        if self.warmup_epochs == 0:
            return self.beta_max
        return float(min(self.beta_max, self.beta_max * epoch / self.warmup_epochs))

"""---
## 3. VAE Architecture
"""

class Sampling(layers.Layer):
    """Reparameterisation trick: z = mu + sigma * epsilon."""
    def call(self, inputs, training=None):
        mu, logvar = inputs
        eps = tf.random.normal(shape=tf.shape(mu))
        sigma = tf.exp(0.5 * logvar)
        return mu + sigma * eps


def build_encoder(config: VAEConfig):
    """
    Encoder: (B, C, H, W) → mu, logvar, z  each of shape (B, latent_dim).

    FIX #3: input shape is channels-first (C, H, W).
    FIX #6: GlobalAveragePooling2D replaces the Flatten+Dense(256) bottleneck.
    FIX #7: Dropout(0.2) applied after enc_dense.
    """
    h, w = config.image_size
    x_in = keras.Input(shape=(config.in_channels, h, w), name="encoder_input")

    x = x_in
    for i, f in enumerate(config.encoder_filters):
        x = layers.Conv2D(
            f, kernel_size=3, strides=2, padding="same",
            data_format="channels_first",
            name=f"enc_conv_{i}"
        )(x)
        x = layers.BatchNormalization(axis=1, name=f"enc_bn_{i}")(x)
        x = layers.LeakyReLU(negative_slope=0.2, name=f"enc_lrelu_{i}")(x)

    # After 4 stride-2 convolutions on 240×240 → spatial size is 15×15
    x = layers.GlobalAveragePooling2D(data_format="channels_first", name="enc_gap")(x)
    x = layers.Dense(512, activation="relu", name="enc_dense")(x)
    x = layers.Dropout(config.dropout_rate, name="enc_dropout")(x)

    mu     = layers.Dense(config.latent_dim, name="z_mu")(x)
    logvar = layers.Dense(config.latent_dim, name="z_logvar")(x)
    z      = Sampling(name="z_sampling")([mu, logvar])

    return keras.Model(x_in, [mu, logvar, z], name="encoder")


def build_decoder(config: VAEConfig):
    """
    Decoder: z (B, latent_dim) → reconstructed image (B, out_channels, 240, 240).

    FIX #1 (CRITICAL): output activation is None (linear) instead of sigmoid.
        Sigmoid squashes output to [0,1] but z-scored data spans ~ [-3, +4].
        Linear activation lets the decoder produce any real value, required
        for MSE regression on z-scored data.
    FIX #7: Dropout(0.2) applied after dec_dense_0.
    FIX #8: Resizing layer removed. 4 stride-2 transposed convolutions on a
        15×15 feature map produce exactly 240×240 (15→30→60→120→240).
    """
    z_in = keras.Input(shape=(config.latent_dim,), name="z_input")

    x = layers.Dense(512, activation="relu", name="dec_dense_0")(z_in)
    x = layers.Dropout(0.2, name="dec_dropout")(x)
    x = layers.Dense(256 * 15 * 15, activation="relu", name="dec_dense_1")(x)
    x = layers.Reshape((256, 15, 15), name="dec_reshape")(x)

    for i, f in enumerate(config.decoder_filters):
        x = layers.Conv2DTranspose(
            f, kernel_size=3, strides=2, padding="same",
            data_format="channels_first",
            name=f"dec_deconv_{i}"
        )(x)
        x = layers.BatchNormalization(axis=1, name=f"dec_bn_{i}")(x)
        x = layers.LeakyReLU(negative_slope=0.2, name=f"dec_lrelu_{i}")(x)

    # FIX #1: activation=None (linear) — was "sigmoid"
    x = layers.Conv2D(
        config.out_channels, kernel_size=3, padding="same",
        activation=None,
        data_format="channels_first",
        name="decoder_output_conv"
    )(x)

    return keras.Model(z_in, x, name="decoder")


class ConditionalVAE(keras.Model):
    def __init__(self, config: VAEConfig, **kwargs):
        super().__init__(**kwargs)
        self.config  = config
        self.encoder = build_encoder(config)
        self.decoder = build_decoder(config)

        self.total_loss_tracker = keras.metrics.Mean(name="total_loss")
        self.recon_loss_tracker = keras.metrics.Mean(name="recon_loss")
        self.kl_loss_tracker    = keras.metrics.Mean(name="kl_loss")

    @property
    def metrics(self):
        return [self.total_loss_tracker, self.recon_loss_tracker, self.kl_loss_tracker]

    def call(self, x, training=False):
        mu, logvar, z = self.encoder(x, training=training)
        recon         = self.decoder(z, training=training)
        return recon, mu, logvar, z

    def compute_losses(self, x, y, training=False, beta: float = None):
        """
        Compute total VAE loss = recon_loss + beta * kl_loss.

        Parameters
        ----------
        beta : float, optional
            Override config.beta (used by BetaScheduler during real training).
            Defaults to config.beta when not supplied.
        """
        if beta is None:
            beta = self.config.beta

        recon, mu, logvar, z = self(x, training=training)

        # MSE reconstruction loss (channels-first: reduce over axes 1,2,3)
        recon_mse  = tf.reduce_mean(tf.math.squared_difference(y, recon), axis=(1, 2, 3))
        recon_loss = tf.reduce_mean(recon_mse)

        kl_per_sample = -0.5 * tf.reduce_sum(
            1.0 + logvar - tf.square(mu) - tf.exp(logvar), axis=1
        )
        kl_loss    = tf.reduce_mean(kl_per_sample)
        total_loss = recon_loss + beta * kl_loss

        return total_loss, recon_loss, kl_loss, recon, mu, logvar, z

    def train_step_batch(self, optimizer, x, y, beta: float = None):
        """One manual gradient update step."""
        if beta is None:
            beta = self.config.beta

        with tf.GradientTape() as tape:
            total_loss, recon_loss, kl_loss, recon, mu, logvar, z = self.compute_losses(
                x, y, training=True, beta=beta
            )

        grads = tape.gradient(total_loss, self.trainable_variables)
        optimizer.apply_gradients(zip(grads, self.trainable_variables))

        self.total_loss_tracker.update_state(total_loss)
        self.recon_loss_tracker.update_state(recon_loss)
        self.kl_loss_tracker.update_state(kl_loss)

        return {
            "total_loss"  : float(total_loss.numpy()),
            "recon_loss"  : float(recon_loss.numpy()),
            "kl_loss"     : float(kl_loss.numpy()),
            "recon_shape" : tuple(recon.shape),
            "mu_shape"    : tuple(mu.shape),
            "logvar_shape": tuple(logvar.shape),
            "z_shape"     : tuple(z.shape),
        }

"""---
## 4. Load Real Data from Google Drive

"""

import os
import numpy as np # Ensure numpy is imported for functions defined below
import glob # Ensure glob is imported if needed in redefined functions

set_seed(42)

# Redefining load_npz_slice and load_batch here to include the 'image' key
# This overrides the definitions from the config-cell for the current cell's execution.

def load_npz_slice(npz_path: str, target_channel_idx: int):
    """
    Load one preprocessed BraTS slice from a .npz file and return
    channels-first (batch=1) tensors ready for the VAE.

    Expected .npz layout (Yue's preprocessing):
        data["slice"]  →  shape (4, 240, 240)   float32, z-scored
            channel 0 = T1
            channel 1 = T2
            channel 2 = T1ce
            channel 3 = FLAIR

    Parameters
    ----------
    npz_path : str
        Absolute path to the .npz file.
    target_channel_idx : int
        Which channel is the synthesis target (0–3).

    Returns
    -------
    x : np.ndarray  shape (1, 3, 240, 240)  — three input modalities
    y : np.ndarray  shape (1, 1, 240, 240)  — target modality
    """
    data = np.load(npz_path)
    # ── key detection: try common export keys ────────────────────────────────
    # FIX: Add 'image' to the list of recognized keys based on the error message.
    for key in ("slice", "data", "arr_0", "image"):
        if key in data:
            all_channels = data[key]
            break
    else:
        raise KeyError(
            f"Could not find a recognised key in {npz_path}. "
            f"Available keys: {list(data.keys())}"
        )

    if all_channels.shape != (4, 240, 240):
        # Handle case where 'image' might be (240, 240, 4) if channels-last
        # Assuming it should be (4, 240, 240) for channels-first as per notebook convention
        # If the actual data for 'image' is (H, W, C), a transpose would be needed.
        # For now, assuming it conforms to (C, H, W) or can be reshaped.
        if all_channels.ndim == 3 and all_channels.shape[-1] == 4 and all_channels.shape[0] != 4:
            print(f"Warning: 'image' data in {npz_path} has shape {all_channels.shape}, assuming channels-last and transposing.")
            all_channels = np.transpose(all_channels, (2, 0, 1)) # HWC to CHW

        if all_channels.shape != (4, 240, 240):
            raise ValueError(
                f"Expected shape (4, 240, 240) for image data, got {all_channels.shape} in {npz_path} after potential transpose."
            )

    y = all_channels[target_channel_idx : target_channel_idx + 1][np.newaxis]  # (1,1,240,240)
    input_channels = np.delete(all_channels, target_channel_idx, axis=0)        # (3,240,240)
    x = input_channels[np.newaxis]                                               # (1,3,240,240)
    return x.astype(np.float32), y.astype(np.float32)


def load_batch(file_list: list, target_channel_idx: int):
    """
    Stack multiple slices into a single batch tensor.

    Parameters
    ----------
    file_list : list[str]
        Absolute paths to .npz files (one per slice).
    target_channel_idx : int
        Synthesis target channel (0=T1, 1=T2, 2=T1ce, 3=FLAIR).

    Returns
    -------
    X : np.ndarray  shape (N, 3, 240, 240)
    Y : np.ndarray  shape (N, 1, 240, 240)
    """
    xs, ys = [], []
    for path in file_list:
        x, y = load_npz_slice(path, target_channel_idx)
        xs.append(x)
        ys.append(y)
    return np.concatenate(xs, axis=0), np.concatenate(ys, axis=0)

# ── Discover .npz files ───────────────────────────────────────────────────────
all_npz_files = discover_npz_files(DATA_DIR)
print(f"Found {len(all_npz_files)} .npz files under {DATA_DIR}")
print("First 5 files:")
for p in all_npz_files[:20]:
    print(" ", p)

# ── Load a small batch (adjust BATCH_SIZE to match available VRAM) ────────────
BATCH_SIZE = 2
batch_files = all_npz_files[:BATCH_SIZE]

# Channel index mapping:
#   0 = T1  |  1 = T2  |  2 = T1ce  |  3 = FLAIR
CHANNEL_MAP = {0: "T1", 1: "T2", 2: "T1ce", 3: "FLAIR"}

# Load each modality as a (N, 1, 240, 240) array by treating the other
# channels as the "inputs" and this channel as the "target".
# We collect all four channels by loading with each as target in turn.
_channels = {}
for ch_idx, ch_name in CHANNEL_MAP.items():
    _, y = load_batch(batch_files, target_channel_idx=ch_idx)
    _channels[ch_name] = y  # shape (N, 1, 240, 240)

t1    = _channels["T1"]
t2    = _channels["T2"]
t1ce  = _channels["T1ce"]
flair = _channels["FLAIR"]

print("\nChannels-first shapes (batch, C, H, W):")
print("t1   :", t1.shape)
print("t2   :", t2.shape)
print("t1ce :", t1ce.shape)
print("flair:", flair.shape)

"""---
## 5. Build the Three Synthesis Tasks
"""

# Task A: synthesise T1ce from T1, T2, FLAIR
X_t1ce  = np.concatenate([t1, t2, flair], axis=1).astype(np.float32)   # (B, 3, 240, 240)
Y_t1ce  = t1ce.astype(np.float32)                                        # (B, 1, 240, 240)

# Task B: synthesise FLAIR from T1, T2, T1ce
X_flair = np.concatenate([t1, t2, t1ce], axis=1).astype(np.float32)
Y_flair = flair.astype(np.float32)

# Task C: synthesise T1 + T2 jointly from T1ce, FLAIR
X_t1t2  = np.concatenate([t1ce, flair], axis=1).astype(np.float32)      # (B, 2, 240, 240)
Y_t1t2  = np.concatenate([t1, t2], axis=1).astype(np.float32)           # (B, 2, 240, 240)

print("Task A  input / output:", X_t1ce.shape,  Y_t1ce.shape)
print("Task B  input / output:", X_flair.shape, Y_flair.shape)
print("Task C  input / output:", X_t1t2.shape,  Y_t1t2.shape)

"""---
## 6. Task A — T1ce Synthesis (Inputs: T1, T2, FLAIR)
"""

config_a  = VAEConfig(image_size=(240, 240), in_channels=3, out_channels=1,
                      latent_dim=128, batch_size=BATCH_SIZE)
model_a   = ConditionalVAE(config_a)

# FIX #11 (LOW): clipnorm=1.0 prevents gradient explosion from KL spikes
optimizer_a = keras.optimizers.Adam(learning_rate=config_a.learning_rate, clipnorm=1.0)

# FIX #4: BetaScheduler — epoch=10 gives fully warmed-up beta=1.0 for this test
scheduler   = BetaScheduler(beta_max=1.0, warmup_epochs=10)
beta_now    = scheduler.get(epoch=10)

total_loss, recon_loss, kl_loss, recon, mu, logvar, z = model_a.compute_losses(
    X_t1ce, Y_t1ce, training=False, beta=beta_now
)

print("\nTask A — forward pass")
print("  Input shape    :", X_t1ce.shape)
print("  Target shape   :", Y_t1ce.shape)
print("  Recon shape    :", recon.shape)
print("  Mu shape       :", mu.shape)
print("  Logvar shape   :", logvar.shape)
print("  Latent z shape :", z.shape)
print("  Total loss     :", float(total_loss.numpy()))
print("  Recon loss     :", float(recon_loss.numpy()))
print("  KL loss        :", float(kl_loss.numpy()))

train_logs_a = model_a.train_step_batch(optimizer_a, X_t1ce, Y_t1ce, beta=beta_now)
print("\nTask A — one training step:")
print(train_logs_a)

"""---
## 7. Task B — FLAIR Synthesis (Inputs: T1, T2, T1ce)
"""

config_b    = VAEConfig(image_size=(240, 240), in_channels=3, out_channels=1,
                        latent_dim=128, batch_size=BATCH_SIZE)
model_b     = ConditionalVAE(config_b)
optimizer_b = keras.optimizers.Adam(learning_rate=config_b.learning_rate, clipnorm=1.0)

total_loss, recon_loss, kl_loss, recon, mu, logvar, z = model_b.compute_losses(
    X_flair, Y_flair, training=False, beta=beta_now
)

print("\nTask B — forward pass")
print("  Input shape    :", X_flair.shape)
print("  Target shape   :", Y_flair.shape)
print("  Recon shape    :", recon.shape)
print("  Mu shape       :", mu.shape)
print("  Logvar shape   :", logvar.shape)
print("  Latent z shape :", z.shape)
print("  Total loss     :", float(total_loss.numpy()))
print("  Recon loss     :", float(recon_loss.numpy()))
print("  KL loss        :", float(kl_loss.numpy()))

train_logs_b = model_b.train_step_batch(optimizer_b, X_flair, Y_flair, beta=beta_now)
print("\nTask B — one training step:")
print(train_logs_b)

"""---
## 8. Task C — Joint T1 + T2 Synthesis (Inputs: T1ce, FLAIR)

> **Note (FIX #12):** Task C is harder than single-modality synthesis because the decoder must learn two different modality distributions simultaneously. Expect more training epochs or a larger `latent_dim` compared with Tasks A/B.
"""

config_c    = VAEConfig(image_size=(240, 240), in_channels=2, out_channels=2,
                        latent_dim=128, batch_size=BATCH_SIZE)
model_c     = ConditionalVAE(config_c)
optimizer_c = keras.optimizers.Adam(learning_rate=config_c.learning_rate, clipnorm=1.0)

total_loss, recon_loss, kl_loss, recon, mu, logvar, z = model_c.compute_losses(
    X_t1t2, Y_t1t2, training=False, beta=beta_now
)

print("\nTask C — forward pass")
print("  Input shape    :", X_t1t2.shape)
print("  Target shape   :", Y_t1t2.shape)
print("  Recon shape    :", recon.shape)
print("  Mu shape       :", mu.shape)
print("  Logvar shape   :", logvar.shape)
print("  Latent z shape :", z.shape)
print("  Total loss     :", float(total_loss.numpy()))
print("  Recon loss     :", float(recon_loss.numpy()))
print("  KL loss        :", float(kl_loss.numpy()))

train_logs_c = model_c.train_step_batch(optimizer_c, X_t1t2, Y_t1t2, beta=beta_now)
print("\nTask C — one training step:")
print(train_logs_c)

"""---
## 9. Learning-Rate Scheduler Stub (FIX #10)

Uncomment and activate the block below when transitioning from dummy tests to real training.  
`ReduceLROnPlateau` matches the scheduler used by David's U-Net (per INT-04 spec).
"""

# Uncomment for real training:

'''lr_callback = keras.callbacks.ReduceLROnPlateau(
    monitor  = "val_total_loss",
    factor   = 0.5,
    patience = 5,
    min_lr   = 1e-6,
    verbose  = 1,
)'''

# Pass to model.fit() or call manually inside a custom training loop:
# if epoch % check_interval == 0:
#      lr_callback.on_epoch_end(epoch, logs)

print("LR scheduler stub ready — uncomment for real training.")

"""## 11. Full Training Loop Example with LR Scheduler

This section demonstrates how to set up a basic training loop for Task A, incorporating the `BetaScheduler` for KL divergence annealing and the `ReduceLROnPlateau` callback for learning rate adjustment. Note that for a real training scenario, you would typically have a dataset loader that provides multiple batches per epoch and a validation set for monitoring `val_total_loss`.
"""

epochs = 25
warmup_epochs = 3 # Beta will anneal from 0 to 1 over these epochs

# Re-initialize model_a and optimizer_a for a fresh training run
config_a  = VAEConfig(image_size=(240, 240), in_channels=3, out_channels=1,
                      latent_dim=128, batch_size=BATCH_SIZE)
model_a   = ConditionalVAE(config_a)
optimizer_a = keras.optimizers.Adam(learning_rate=config_a.learning_rate, clipnorm=1.0)

beta_scheduler = BetaScheduler(beta_max=config_a.beta, warmup_epochs=warmup_epochs)
lr_callback_instance = keras.callbacks.ReduceLROnPlateau(
    monitor  = "total_loss", # For this example, we'll monitor train total_loss
    factor   = 0.5,
    patience = 2,
    min_lr    = 1e-6,
    verbose  = 1,
    mode     = 'min' # FIX: Added mode='min' to specify that total_loss should be minimized
)
# FIX: Manually assign the model to the callback instance.
lr_callback_instance.set_model(model_a)
# FIX: Since set_optimizer is not available, explicitly assign the optimizer to the model.
model_a.optimizer = optimizer_a

history = []


print(f"Starting training loop for {epochs} epochs...")

for epoch in range(1, epochs + 1):
    current_beta = beta_scheduler.get(epoch)
    x_batch = X_t1ce
    y_batch = Y_t1ce

    train_metrics = model_a.train_step_batch(optimizer_a, x_batch, y_batch, beta=current_beta)

    # ✅ FIX: fire callback BEFORE reading lr, and use keras.backend.get_value
    lr_callback_instance.on_epoch_end(epoch, logs={'total_loss': train_metrics['total_loss']})

    epoch_logs = {
        "epoch":      epoch,
        "beta":       current_beta,
        "total_loss": train_metrics["total_loss"],
        "recon_loss": train_metrics["recon_loss"],
        "kl_loss":    train_metrics["kl_loss"],
        "lr":         float(keras.backend.get_value(optimizer_a.learning_rate)),  # Fixed attribute access
    }
    history.append(epoch_logs)

    print(f"Epoch {epoch}/{epochs} | Beta: {current_beta:.4f} | "
          f"Total Loss: {train_metrics['total_loss']:.4f} | "
          f"Recon Loss: {train_metrics['recon_loss']:.4f} | "
          f"KL Loss: {train_metrics['kl_loss']:.4f} | "
          f"LR: {epoch_logs['lr']:.6f}")

    # Apply LR scheduler (monitoring 'total_loss' for this demo)
    # In a real scenario, you'd pass validation metrics here.
    # Redundant call removed

print("Training loop finished.")

"""---
## 10. Quick Reconstruction Preview
"""

fig, axes = plt.subplots(2, 3, figsize=(10, 6))

pred_a, _, _, _ = model_a(X_t1ce, training=False)
# FIX #3: slice channel dim=1 (channels-first) — not dim=-1
axes[0, 0].imshow(np.mean(X_t1ce[0], axis=0), cmap="gray")   # mean over C axis
axes[0, 0].set_title("Task A — input (mean)")
axes[0, 1].imshow(Y_t1ce[0, 0], cmap="gray")
axes[0, 1].set_title("Task A — target")
axes[0, 2].imshow(pred_a.numpy()[0, 0], cmap="gray")
axes[0, 2].set_title("Task A — prediction")

pred_c, _, _, _ = model_c(X_t1t2, training=False)
axes[1, 0].imshow(np.mean(X_t1t2[0], axis=0), cmap="gray")
axes[1, 0].set_title("Task C — input (mean)")
axes[1, 1].imshow(Y_t1t2[0, 0], cmap="gray")
axes[1, 1].set_title("Task C — target ch0 (T1)")
axes[1, 2].imshow(pred_c.numpy()[0, 0], cmap="gray")
axes[1, 2].set_title("Task C — pred ch0")

for row in axes:
    for ax in row:
        ax.axis("on")

plt.suptitle("Reconstruction preview (untrained models)", fontsize=13, y=1.01)
plt.tight_layout()
plt.show()

"""---
## Summary

This notebook is a **sanity-check** for the Conditional Multimodal VAE architecture. It verifies:

- ✅ Model builds without error
- ✅ Forward pass succeeds for all three tasks
- ✅ Loss computation (MSE + KL) succeeds
- ✅ One custom gradient training step succeeds
- ✅ Output tensors are exactly `(batch, out_channels, 240, 240)`

Tensors are kept in **channels-first** `(batch, C, H, W)` format throughout, matching Yue's preprocessing output with no intermediate transposes.
"""